### ISSUE TITLE
can't install the lib properly

### ISSUE THREAD

**Issue by AndrewEastwood** [clns/node-commit-msg#2]
I got lots of errors in my terminal:

```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild
gyp ERR! cwd C:\Projects\testproject\node_modules\commit-msg\node_modules\java
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing java@0.5.5

> commit-msg@0.2.1 postinstall C:\Projects\testproject\node_modules\commit-msg
> npm run hook


> commit-msg@0.2.1 hook C:\Projects\testproject\node_modules\commit-msg
> node lib/setup

C:\Projects\testproject\node_modules\commit-msg\lib\setup.js:119
                        throw e;
                        ^

Error: EPERM: operation not permitted, symlink '..\..\node_modules\commit-msg\bin\commit-msg' -> 'C:\Projects\testproject\.git\hooks\commit-msg'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:902:18)
    at setupHook (C:\Projects\testproject\node_modules\commit-msg\lib\setup.js:116:14)
    at Object.<anonymous> (C:\Projects\testproject\node_modules\commit-msg\lib\setup.js:127:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "hook"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! commit-msg@0.2.1 hook: `node lib/setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the commit-msg@0.2.1 hook script 'node lib/setup'.
npm ERR! This is most likely a problem with the commit-msg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/setup
npm ERR! You can get their info via:
npm ERR!     npm owner ls commit-msg
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\testproject\node_modules\commit-msg\npm-debug.log
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! commit-msg@0.2.1 postinstall: `npm run hook`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the commit-msg@0.2.1 postinstall script 'npm run hook'.
npm ERR! This is most likely a problem with the commit-msg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run hook
npm ERR! You can get their info via:
npm ERR!     npm owner ls commit-msg
npm ERR! There is likely additional logging output above.

> commit-msg@0.2.1 preuninstall C:\Projects\testproject\node_modules\commit-msg
> npm run hook-uninstall


> commit-msg@0.2.1 hook-uninstall C:\Projects\testproject\node_modules\commit-msg
> node lib/setup uninstall


npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\testproject\npm-debug.log
```

Any suggestions how to fix that?

**Comment by AndrewEastwood** [comment]
I also happen on my laptop with ubuntu:

```
user@laptop:~/testproject$ npm install
npm WARN engine commit-msg@0.2.1: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
-
> java@0.5.5 install /home/user/testproject/node_modules/commit-msg/node_modules/java
> node-gyp rebuild

[node-java] Error: not found: javac
gyp: Call to 'node findJavaHome.js' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.2.0-88-generic-pae
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/testproject/node_modules/commit-msg/node_modules/java
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing java@0.5.5

> commit-msg@0.2.1 postinstall /home/user/testproject/node_modules/commit-msg
> npm run hook


> commit-msg@0.2.1 hook /home/user/testproject/node_modules/commit-msg
> node lib/setup

Install hook at /home/user/testproject/.git/hooks/commit-msg
Install hook at /home/user/testproject/.git/hooks/update
commit-msg@0.2.1 node_modules/commit-msg
├── clone@1.0.2
├── semver@4.3.6
├── commander@2.8.1 (graceful-readlink@1.0.1)
└── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
```

**Comment by clns** [comment]
On your laptop, make sure you have `java` available (see the [prerequisites](https://github.com/clns/node-commit-msg#prerequisites)). Java is required by the [Stanford Parser](http://nlp.stanford.edu/software/lex-parser.shtml) which is used to detect non-imperative verbs.

On windows, it can't find python, but that's an [optional prerequisite](https://github.com/clns/node-commit-msg/blob/master/CONTRIBUTING.md#2-install-the-optional-prerequisites), because node-java is an optional dependency, so you can ignore the first errors.

The real problem is it cannot create the symlink due to a permission denied error: 

`Error: EPERM: operation not permitted, symlink '..\..\node_modules\commit-msg\bin\commit-msg' -> 'C:\Projects\testproject\.git\hooks\commit-msg'`.

Maybe your user doesn't have access to create symlinks. Try running your cmd or PowerShell as administrator and try again.

**Comment by AndrewEastwood** [comment]
ok. we'll try to run it with admin perms and then let you know results. Thanks.

**Comment by AndrewEastwood** [comment]
hey @clns. It helped! Thanks!

**Comment by clns** [comment]
:+1:
